server:
  port: 9000
az:
  rack: rack1
  zone: zone1

file:
  basePath: E:\MinFSWrite

#curator配置
curator:
  connectString: localhost:2181 # zookeeper 地址
  retryCount: 1 # 重试次数
  elapsedTimeMs: 2000 # 重试间隔时间
  sessionTimeoutMs: 60000 # session超时时间
  connectionTimeoutMs: 10000 # 连接超时时间

zookeeper:
  addr: localhost:2181
